--- 
- name: Setup Nginx on Linux Server
  hosts: webservers
  become: true
  tasks:
    - name: Update apt package index
      apt:
        update_cache: yes

    - name: Upgrade all packages
      apt:
        upgrade: yes

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Remove file (delete file)
      ansible.builtin.file:
        path: /etc/nginx/sites-available/default
        state: absent

    - name: Create file and add contents
      copy:
      dest: /etc/nginx/sites-available/default
      content: |
        server {
            listen 80 default_server;
            listen [::]:80 default_server;

            root /var/www/html;
            index index.html index.htm index.nginx-debian.html;

            server_name _;

            location / {
                proxy_pass http://localhost:3000;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }
        }

    - name: Test Nginx configuration
      command: nginx -t
      register: nginx_test
    - debug:
        msg: "Nginx configuration test output: {{ nginx_test.stdout }}"

    - name: Ensure Nginx is running and enabled
      service:
        name: nginx
        state: started
        enabled: true

    - name: Reload Nginx to apply changes
      service:
        name: nginx
        state: restart