---
- name: Setup Node.js Environment on Ubuntu Server
  hosts: chatapp
  become: true
  vars:
    packages: 
      - nodejs
      - build-essential
  tasks:
    - name: Add NodeSource APT repository
      shell: |
        curl -sL https://deb.nodesource.com/setup_20.x -o nodesource_setup.sh | bash nodesource_setup.sh

    - name: Install nodejs, npm and build-essential
      apt:
        name: "{{ packages }}"
        state: present

    - name: Install pm2 globally
      npm:
        name: pm2
        global: yes